### ISSUE TITLE
outline shows no nesting

### ISSUE THREAD

**Issue by jurgenvinju** [cwi-swat/rascal-vscode#23]

**Comment by DavyLandman** [comment]
True, the `[documentSymbols](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol)` requests supports a tree as result, but that is meant for cases where it's also nesting in the source file (as every level of the tree has to have a range). So for example a class with it's nested functions/fields.

I've added #13 so that we can switch to a more LSP like outline, also improving the labels.

**Comment by jurgenvinju** [comment]
this requires a rewrite of the outline feature in the Rascal IDE support to use the new interface in util::LanguageServer. Let's park this until we switch the Rascal LSP to that parametric interface. In the meantime we outline is functional and works also in Eclipse still.
